### ISSUE TITLE
Unit is not copied if the unit has no abbreviation set

### ISSUE THREAD

**Issue by ykorzikowski** [felixschndr/mealie-bring-api#1] opened 2024-05-25 17:16 UTC
Hi there, 

first thank you for this nice integration with mealie :) this was just what I searched. 

I found when adding a dish to bring, the units are not copied over. Do you have an idea why? See my test below:

![IMG_6875](https://github.com/felixschndr/mealie-bring-api/assets/20556547/7a4ef71b-0439-4f43-b13e-81e56b5e72b5)
<img width="564" alt="Screenshot 2024-05-25 at 19 14 17" src="https://github.com/felixschndr/mealie-bring-api/assets/20556547/a8f93b15-e7ea-4d53-aad5-58b65548e8bd">

```
{
  "id": "45d7459e-251e-4178-a276-daa2a3ea2a10",
  "userId": "7544c306-88b9-49cb-8f8e-98302391613f",
  "groupId": "59e5359d-9c92-4d0b-85f7-f6e9620974a1",
  "name": "Tomaten Rucola Flammkuchen",
  "slug": "tomaten-rucola-flammkuchen",
  "image": "182",
  "recipeYield": "2",
  "totalTime": "30",
  "prepTime": "15",
  "cookTime": null,
  "performTime": "15",
  "description": "",
  "recipeCategory": [],
  "tags": [],
  "tools": [],
  "rating": null,
  "orgURL": null,
  "dateAdded": "2024-05-25",
  "dateUpdated": "2024-05-25T18:53:17.066876",
  "createdAt": "2024-05-25T18:48:06.147132",
  "updateAt": "2024-05-25T18:48:06.147133",
  "lastMade": null,
  "recipeIngredient": [
    {
      "quantity": 125,
      "unit": {
        "id": "6f9f83b6-3631-4538-9cb0-f9d916c1fd65",
        "name": "Gramm",
        "pluralName": null,
        "description": "",
        "extras": {},
        "fraction": true,
        "abbreviation": "",
        "pluralAbbreviation": "",
        "useAbbreviation": false,
        "aliases": [],
        "createdAt": "2024-05-25T18:37:01.069500",
        "updateAt": "2024-05-25T18:37:01.069504"
      },
      "food": {
        "id": "96cf3773-4f52-4ac0-9fbe-69593e8b7df0",
        "name": "Mehl",
        "pluralName": null,
        "description": "",
        "extras": {},
        "labelId": null,
        "aliases": [],
        "label": null,
        "createdAt": "2024-05-25T16:48:24.204939",
        "updateAt": "2024-05-25T16:48:24.204943"
      },
      "note": "Mehr",
      "isFood": true,
      "disableAmount": false,
      "display": "125 Gramm Mehl Mehr",
      "title": null,
      "originalText": null,
      "referenceId": "84277a9d-d58c-4705-9160-4cd85e1b3ff9"
    },
    {
      "quantity": 63,
      "unit": {
        "id": "bcc47a8a-7a71-45e6-857a-ebc12dd60451",
        "name": "ml",
        "pluralName": null,
        "description": "",
        "extras": {},
        "fraction": true,
        "abbreviation": "",
        "pluralAbbreviation": "",
        "useAbbreviation": false,
        "aliases": [],
        "createdAt": "2024-05-25T18:38:00.292162",
        "updateAt": "2024-05-25T18:38:00.292165"
      },
      "food": {
        "id": "66bd4880-332e-4786-9c67-c968ce141837",
        "name": "Wasser",
        "pluralName": null,
        "description": "",
        "extras": {},
        "labelId": null,
        "aliases": [],
        "label": null,
        "createdAt": "2024-05-25T18:49:39.409301",
        "updateAt": "2024-05-25T18:49:39.409305"
      },
      "note": "Wasser",
      "isFood": true,
      "disableAmount": false,
      "display": "63 ml Wasser Wasser",
      "title": "",
      "originalText": null,
      "referenceId": "27bd76f4-eefd-4d2c-8112-fba5785af68c"
    },
    {
      "quantity": 1,
      "unit": {
        "id": "e706a2bc-7b49-4d2f-af06-ef48a8843f7d",
        "name": "EL",
        "pluralName": null,
        "description": "",
        "extras": {},
        "fraction": true,
        "abbreviation": "",
        "pluralAbbreviation": "",
        "useAbbreviation": false,
        "aliases": [],
        "createdAt": "2024-05-25T18:50:06.694731",
        "updateAt": "2024-05-25T18:50:06.694734"
      },
      "food": {
        "id": "945af386-f56e-4090-ab08-e8c20c6f72e2",
        "name": "Olivenöl",
        "pluralName": null,
        "description": "",
        "extras": {},
        "labelId": null,
        "aliases": [],
        "label": null,
        "createdAt": "2024-05-25T16:48:24.721477",
        "updateAt": "2024-05-25T16:48:24.721481"
      },
      "note": "Olivenöl ",
      "isFood": true,
      "disableAmount": false,
      "display": "1 EL Olivenöl Olivenöl",
      "title": "",
      "originalText": null,
      "referenceId": "7bc6e306-4eb3-4cf5-9f13-83ce69533d31"
    },
    {
      "quantity": 2,
      "unit": {
        "id": "9f8ea323-5381-4cc5-9141-5824a5cc1784",
        "name": "Prise",
        "pluralName": null,
        "description": "",
        "extras": {},
        "fraction": true,
        "abbreviation": "",
        "pluralAbbreviation": "",
        "useAbbreviation": false,
        "aliases": [],
        "createdAt": "2024-05-25T18:37:38.795661",
        "updateAt": "2024-05-25T18:37:38.795664"
      },
      "food": {
        "id": "ebb97c2b-cb82-416c-9887-351c057fb45c",
        "name": "Salz",
        "pluralName": null,
        "description": "",
        "extras": {},
        "labelId": null,
        "aliases": [],
        "label": null,
        "createdAt": "2024-05-25T16:48:24.139268",
        "updateAt": "2024-05-25T16:48:24.139271"
      },
      "note": "Salz",
      "isFood": true,
      "disableAmount": false,
      "display": "2 Prise Salz Salz",
      "title": "",
      "originalText": null,
      "referenceId": "50f83008-6962-4e24-b4f2-0a294a902ce1"
    },
    {
      "quantity": 100,
      "unit": {
        "id": "6f9f83b6-3631-4538-9cb0-f9d916c1fd65",
        "name": "Gramm",
        "pluralName": null,
        "description": "",
        "extras": {},
        "fraction": true,
        "abbreviation": "",
        "pluralAbbreviation": "",
        "useAbbreviation": false,
        "aliases": [],
        "createdAt": "2024-05-25T18:37:01.069500",
        "updateAt": "2024-05-25T18:37:01.069504"
      },
      "food": {
        "id": "b9e1ceac-3e37-47a7-b20a-edce4be0311f",
        "name": "Crème fraîche",
        "pluralName": null,
        "description": "",
        "extras": {},
        "labelId": null,
        "aliases": [],
        "label": null,
        "createdAt": "2024-05-25T18:50:24.999647",
        "updateAt": "2024-05-25T18:50:24.999650"
      },
      "note": "Crème fraîche",
      "isFood": true,
      "disableAmount": false,
      "display": "100 Gramm Crème fraîche Crème fraîche",
      "title": "",
      "originalText": null,
      "referenceId": "7ca66be8-4a4b-4c72-ba84-cb7c64dfbd6e"
    },
    {
      "quantity": 50,
      "unit": {
        "id": "6f9f83b6-3631-4538-9cb0-f9d916c1fd65",
        "name": "Gramm",
        "pluralName": null,
        "description": "",
        "extras": {},
        "fraction": true,
        "abbreviation": "",
        "pluralAbbreviation": "",
        "useAbbreviation": false,
        "aliases": [],
        "createdAt": "2024-05-25T18:37:01.069500",
        "updateAt": "2024-05-25T18:37:01.069504"
      },
      "food": {
        "id": "8c2e6b98-3c94-46ce-af24-50bbe1f79113",
        "name": "Schmand",
        "pluralName": null,
        "description": "",
        "extras": {},
        "labelId": null,
        "aliases": [],
        "label": null,
        "createdAt": "2024-05-25T18:50:45.677905",
        "updateAt": "2024-05-25T18:50:45.677908"
      },
      "note": "Schmand",
      "isFood": true,
      "disableAmount": false,
      "display": "50 Gramm Schmand Schmand",
      "title": "",
      "originalText": null,
      "referenceId": "ce6353b7-8a36-471a-8ea0-7ba0a980ea18"
    },
    {
      "quantity": 2,
      "unit": {
        "id": "aef6d4b4-f16e-474a-b342-a38ce4218d66",
        "name": "Handvoll",
        "pluralName": null,
        "description": "",
        "extras": {},
        "fraction": true,
        "abbreviation": "",
        "pluralAbbreviation": "",
        "useAbbreviation": false,
        "aliases": [],
        "createdAt": "2024-05-25T18:50:53.191840",
        "updateAt": "2024-05-25T18:50:53.191844"
      },
      "food": {
        "id": "c7fe6213-3f77-4d85-b176-47d703e3f99a",
        "name": "Kirschtomaten",
        "pluralName": null,
        "description": "",
        "extras": {},
        "labelId": null,
        "aliases": [],
        "label": null,
        "createdAt": "2024-05-25T18:51:02.778271",
        "updateAt": "2024-05-25T18:51:02.778275"
      },
      "note": "Kirschtomaten",
      "isFood": true,
      "disableAmount": false,
      "display": "2 Handvoll Kirschtomaten Kirschtomaten",
      "title": "",
      "originalText": null,
      "referenceId": "5cb5e289-f898-4dc6-9ef2-272c6951aa33"
    },
    {
      "quantity": 6,
      "unit": {
        "id": "e428461f-d541-4e5b-acb7-978f57c48f41",
        "name": "Scheiben",
        "pluralName": null,
        "description": "",
        "extras": {},
        "fraction": true,
        "abbreviation": "",
        "pluralAbbreviation": "",
        "useAbbreviation": false,
        "aliases": [],
        "createdAt": "2024-05-25T18:51:14.044753",
        "updateAt": "2024-05-25T18:51:14.044756"
      },
      "food": {
        "id": "e8868c5d-83ee-47d4-aa81-60b084ff970f",
        "name": "Parmaschinken",
        "pluralName": null,
        "description": "",
        "extras": {},
        "labelId": null,
        "aliases": [],
        "label": null,
        "createdAt": "2024-05-25T18:51:16.140088",
        "updateAt": "2024-05-25T18:51:16.140091"
      },
      "note": "Parmaschinken",
      "isFood": true,
      "disableAmount": false,
      "display": "6 Scheiben Parmaschinken Parmaschinken",
      "title": "",
      "originalText": null,
      "referenceId": "5c719b66-40e0-4be5-90b3-0796f3ffeef0"
    },
    {
      "quantity": 2,
      "unit": {
        "id": "e706a2bc-7b49-4d2f-af06-ef48a8843f7d",
        "name": "EL",
        "pluralName": null,
        "description": "",
        "extras": {},
        "fraction": true,
        "abbreviation": "",
        "pluralAbbreviation": "",
        "useAbbreviation": false,
        "aliases": [],
        "createdAt": "2024-05-25T18:50:06.694731",
        "updateAt": "2024-05-25T18:50:06.694734"
      },
      "food": {
        "id": "c62fc50b-6ff0-40f0-b274-415916de8b15",
        "name": "Italienische Kräuter",
        "pluralName": null,
        "description": "",
        "extras": {},
        "labelId": null,
        "aliases": [],
        "label": null,
        "createdAt": "2024-05-25T18:51:29.182166",
        "updateAt": "2024-05-25T18:51:29.182170"
      },
      "note": "Italienische Kräuter",
      "isFood": true,
      "disableAmount": false,
      "display": "2 EL Italienische Kräuter Italienische Kräuter",
      "title": "",
      "originalText": null,
      "referenceId": "ebae4a0f-d4ef-4334-91c7-9cbc52fef8e6"
    },
    {
      "quantity": 4,
      "unit": {
        "id": "aef6d4b4-f16e-474a-b342-a38ce4218d66",
        "name": "Handvoll",
        "pluralName": null,
        "description": "",
        "extras": {},
        "fraction": true,
        "abbreviation": "",
        "pluralAbbreviation": "",
        "useAbbreviation": false,
        "aliases": [],
        "createdAt": "2024-05-25T18:50:53.191840",
        "updateAt": "2024-05-25T18:50:53.191844"
      },
      "food": {
        "id": "028c86ec-086b-47af-9c85-b136a33cb82b",
        "name": "Ruccola",
        "pluralName": null,
        "description": "",
        "extras": {},
        "labelId": null,
        "aliases": [],
        "label": null,
        "createdAt": "2024-05-25T18:51:37.648115",
        "updateAt": "2024-05-25T18:51:37.648118"
      },
      "note": "Rucola",
      "isFood": true,
      "disableAmount": false,
      "display": "4 Handvoll Ruccola Rucola",
      "title": "",
      "originalText": null,
      "referenceId": "52575008-f6d7-484a-b28f-a5d63a4dccfd"
    },
    {
      "quantity": 1,
      "unit": {
        "id": "e706a2bc-7b49-4d2f-af06-ef48a8843f7d",
        "name": "EL",
        "pluralName": null,
        "description": "",
        "extras": {},
        "fraction": true,
        "abbreviation": "",
        "pluralAbbreviation": "",
        "useAbbreviation": false,
        "aliases": [],
        "createdAt": "2024-05-25T18:50:06.694731",
        "updateAt": "2024-05-25T18:50:06.694734"
      },
      "food": {
        "id": "f66a89b5-a0dc-41f4-893d-3240ef4756f8",
        "name": "Parmesan",
        "pluralName": null,
        "description": "",
        "extras": {},
        "labelId": null,
        "aliases": [],
        "label": null,
        "createdAt": "2024-05-25T18:51:45.547654",
        "updateAt": "2024-05-25T18:51:45.547657"
      },
      "note": "Parmesan",
      "isFood": true,
      "disableAmount": false,
      "display": "1 EL Parmesan Parmesan",
      "title": "",
      "originalText": null,
      "referenceId": "d1be4317-803e-49f6-9a83-b4d26d4a0ae0"
    },
    {
      "quantity": 1,
      "unit": {
        "id": "9f8ea323-5381-4cc5-9141-5824a5cc1784",
        "name": "Prise",
        "pluralName": null,
        "description": "",
        "extras": {},
        "fraction": true,
        "abbreviation": "",
        "pluralAbbreviation": "",
        "useAbbreviation": false,
        "aliases": [],
        "createdAt": "2024-05-25T18:37:38.795661",
        "updateAt": "2024-05-25T18:37:38.795664"
      },
      "food": {
        "id": "c4ae5021-f10e-4445-959d-a2770424b3e6",
        "name": "Pfeffer",
        "pluralName": null,
        "description": "",
        "extras": {},
        "labelId": null,
        "aliases": [],
        "label": null,
        "createdAt": "2024-05-25T16:48:24.595485",
        "updateAt": "2024-05-25T16:48:24.595488"
      },
      "note": "Pfeffer",
      "isFood": true,
      "disableAmount": false,
      "display": "1 Prise Pfeffer Pfeffer",
      "title": "",
      "originalText": null,
      "referenceId": "1c2297ae-63ce-4024-94b9-9f6409638845"
    }
  ],
  "recipeInstructions": [
    {
      "id": "25c28fc7-374c-4b67-afe3-b6c939acc539",
      "title": "",
      "text": "Ofen auf 250 Grad Ober-/Unterhitze mit Blech vorheizen (damit der Teig schön knusprig wird).",
      "ingredientReferences": []
    },
    {
      "id": "4385819a-e114-4664-9abf-af65b4d66c94",
      "title": "",
      "text": "Für den Teig Mehl mit warmem Wasser, Öl und Salz gut kneten, sehr dünn ausrollen und auf ein Backpapier legen.",
      "ingredientReferences": []
    },
    {
      "id": "959fd977-9818-4807-a145-6ddf42f9dbb6",
      "title": "",
      "text": "Die Crème fraîche, Schmand, Salz und Pfeffer mischen. Tomaten und Schinken schneiden und den Teig mit der Creme bestreichen.",
      "ingredientReferences": []
    },
    {
      "id": "53179423-e42e-4180-9043-d73a19d9a28d",
      "title": "",
      "text": "Den Teig mit Schinken und Tomaten belegen, würzen und auf das vorgeheizte Blech legen. Für 10 - 12 Minuten in den Ofen schieben. Zum Schluss noch Rucola und Parmesan darüber geben.",
      "ingredientReferences": []
    }
  ],
  "nutrition": {
    "calories": null,
    "fatContent": null,
    "proteinContent": null,
    "carbohydrateContent": null,
    "fiberContent": null,
    "sodiumContent": null,
    "sugarContent": null
  },
  "settings": {
    "public": true,
    "showNutrition": false,
    "showAssets": false,
    "landscapeView": false,
    "disableComments": false,
    "disableAmount": false,
    "locked": false
  },
  "assets": [],
  "notes": [],
  "extras": {},
  "comments": []
}
```

https://github.com/felixschndr/mealie-bring-api/blob/f2604821698d1ab988fac8ed6642157760bc12b9/source/ingredient.py#L47

**Comment by felixschndr** [comment] 2024-05-26 09:41
Sadly, I cannot reproduce this. 

1. Do you use the [ingredients amounts](https://raw.githubusercontent.com/felixschndr/mealie-bring-api/main/assets/images/recipe_settings.png)? 
2. It seems weird to me that you have the ingredient in Mealie twice (one in the Name (`63 ml Wasser`) and one in the note (`Wasser`). However this should not make a difference.

I created a branch `debug-units` with some additional log output. You can checkout the branch and run the code from there or use the [docker image](https://github.com/felixschndr/mealie-bring-api/pkgs/container/mealie-bring-api/221058482?tag=debug-units). Would you please be so kind and run the export to Mealie again with the [`LOG_LEVEL` set to `DEBUG`](https://github.com/felixschndr/mealie-bring-api?tab=readme-ov-file#environment-variables) and send me the log output?

**Comment by ykorzikowski** [comment] 2024-05-26 10:13
I removed the notes, but it stays the same. I transferred this receipe from non-ingedients amount to ingredient amounts, that's why. 

And yes, I set `Ingredients amount` like on the Screenshot. 

Just want to try your debug branch, but it result in:

```
services:
    meali-bring-relay:
        env_file:
        - /opt/docker/.mealie-bring-secrets-env
        environment:
            BRING_LIST_NAME: "Meali"
            LOG_LEVEL: "DEBUG"
        image: ghcr.io/felixschndr/mealie-bring-api:debug-units
        restart: always
        ports:
            - "8742:8742"
```

```
ModuleNotFoundError: No module named 'source'
Traceback (most recent call last):
  File "/app/main.py", line 7, in <module>
    from bring_handler import BringHandler
  File "/app/bring_handler.py", line 8, in <module>
    from ingredient import Ingredient
  File "/app/ingredient.py", line 2, in <module>
    from source.logger_mixin import LoggerMixin
ModuleNotFoundError: No module named 'source'
```

**Comment by felixschndr** [comment] 2024-05-26 13:25
> ModuleNotFoundError: No module named 'source'

Dang it, I trusted Pycharm to correctly to the import but here we are :D. Please try again, I fixed the mistake in the image (be sure to run `docker pull` again)

**Comment by ykorzikowski** [comment] 2024-05-26 20:11
Is this log already enough? I guess maybe you not properly get the unit.name property. 

```
[2024-05-26 20:08:56,977] [Ingredient] [DEBUG] [Complete ingredient: {'quantity': 2, 'unit': {'id': 'aef6d4b4-f16e-474a-b342-a38ce4218d66', 'name': 'Handvoll', 'pluralName': None, 'description': '', 'extras': {}, 'fraction': True, 'abbreviation': '', 'pluralAbbreviation': '', 'useAbbreviation': False, 'aliases': [], 'createdAt': '2024-05-25T18:50:53.191840', 'updateAt': '2024-05-25T18:50:53.191844'}, 'food': {'id': 'c7fe6213-3f77-4d85-b176-47d703e3f99a', 'name': 'Kirschtomaten', 'pluralName': None, 'description': '', 'extras': {}, 'labelId': None, 'aliases': [], 'label': None, 'createdAt': '2024-05-25T18:51:02.778271', 'updateAt': '2024-05-25T18:51:02.778275'}, 'note': '', 'isFood': True, 'disableAmount': False, 'display': '2 Handvoll Kirschtomaten', 'title': '', 'originalText': None, 'referenceId': '5cb5e289-f898-4dc6-9ef2-272c6951aa33'}]
[2024-05-26 20:08:56,977] [Ingredient] [DEBUG] [Unit: {'id': 'aef6d4b4-f16e-474a-b342-a38ce4218d66', 'name': 'Handvoll', 'pluralName': None, 'description': '', 'extras': {}, 'fraction': True, 'abbreviation': '', 'pluralAbbreviation': '', 'useAbbreviation': False, 'aliases': [], 'createdAt': '2024-05-25T18:50:53.191840', 'updateAt': '2024-05-25T18:50:53.191844'}]
[2024-05-26 20:08:56,977] [Ingredient] [DEBUG] [In if: ]
[2024-05-26 20:08:56,977] [Ingredient] [DEBUG] [Specification afterwards: 2]
[2024-05-26 20:08:56,977] [BringHandler] [DEBUG] [Adding ingredient to Bring: Kirschtomaten (2)]
[2024-05-26 20:08:57,627] [python_bring_api.bring] [DEBUG] [Response from https://api.getbring.com/rest/v2/bringlists/***: 204]
```

**Comment by felixschndr** [comment] 2024-05-26 20:53
Thank you for the log. Yes, it is enough. I understand the issue and implemented a fix. A new image is available (still on the `debug-units` branch). Please test it (remember to `docker pull`) and give me feedback whether your issue is solved.

**Comment by ykorzikowski** [comment] 2024-05-27 16:42
Hi my friend, 

I tested it again and now its working :) Big thank you.

**Comment by felixschndr** [comment] 2024-05-27 20:43
Great, I will merge the fix into `main` in the next few days

**Comment by felixschndr** [comment] 2024-05-30 12:23
I reworked the ingredient parsing a little. @ykorzikowski Would you be so kind and install the latest version of the `debug-units` branch and test if it still works as expected? Thank you!

**Comment by ykorzikowski** [comment] 2024-05-31 21:46
Hi @felixschndr , what did you changed? I just did my shopping list but I remember the last version was a bit prettier putting the amount in the sub-description (see screenshot, old is green new is red).

 
![IMG_6883](https://github.com/felixschndr/mealie-bring-api/assets/20556547/90fed133-799a-43c3-990b-83b996da0b32)
![IMG_6882](https://github.com/felixschndr/mealie-bring-api/assets/20556547/baa935b3-f382-45b3-8cd5-2b029cd7903d)

**Comment by felixschndr** [comment] 2024-06-07 06:21
> what did you changed?

Some code that parses the input from mealie.

----



> I just did my shopping list but I remember the last version was a bit prettier putting the amount in the sub-description

Okay, thank you. This change is not intended, I will take a look why this happens and fix it in the next few days

**Comment by felixschndr** [comment] 2024-06-15 11:55
Hey @ykorzikowski, I just cam to have a look at this again. Sadly, I cannot reproduce the issue you are having. When I run the docker image with the newest image, the amount gets added to the sub-description (like in your red screenshot). Would you be so kind and run the test again with the `LOG_LEVEL` set to `DEBUG` and send me the log afterwards?

The command would be 
```bash
docker pull ghcr.io/felixschndr/mealie-bring-api:debug-units # Ensure you have the latest image

docker run \
    -e BRING_USERNAME="myuser@myemailprovider.com" \
    -e BRING_PASSWORD="my super secret password" \
    -e BRING_LIST_NAME="My shopping list with spaces" \
    -e LOG_LEVEL=DEBUG
    -p 1234:8742 \
    ghcr.io/felixschndr/mealie-bring-api:debug-units
```

Thank you very much!

**Comment by felixschndr** [comment] 2024-07-04 21:01
@ykorzikowski Have you been able to test this?

**Comment by felixschndr** [comment] 2024-07-20 10:36
Since this works for me and I have not heard any feedback from you I merged this now. If you have any further issues please let me know

**Closed** 2024-07-20 10:35 UTC
Labels: bug

**Comment by ykorzikowski** [comment] 2024-07-20 17:38
Hi Felix, I forget to reply you. Was enjoying that finally the weather was stable sunny a few days. Yes, now its working perfect :) Just checked the latest release. Thank you very much.

**Comment by felixschndr** [comment] 2024-07-20 18:43
I'm glad to hear that :)
